# Site information
title: Erwin's Blog 
email: erwin@vandervalk.pro
description: Blogging on life, the universe and everything (but mainly tech)
baseurl: ""
url: "https://erwin.vandervalk.pro"

# Site settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"



google_analytics: 
google_ads: 

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
